sudo: false
language: generic
install: scripts/ci/install.sh
script: scripts/ci/test.sh
deploy:
  provider: script
  script: scripts/ci/deploy.sh --branch $TRAVIS_BRANCH --commit_hash $TRAVIS_COMMIT --now_token $NOW_TOKEN --release_hook $SENTRY_WEBHOOK --heroku_token $HEROKU_TOKEN
  on:
    all_branches: true
addons:
  apt:
    sources:
      - heroku
    packages:
      - heroku-toolbelt
