ellie:
  image: minlearn/ellie-corrected
  links:
  - database:database
  environment:
  - SERVER_HOST=xxx.xxx.xxx.xxx
  ports:
  - 4000:4000
  restart: always
  
database:
  image: postgres:9.5
  environment:
  - POSTGRES_PASSWORD=postgres
  restart: always
  
